dfinity/ICRC-1

- ICRC-1.did
- README.md
This change proposes an extensible way for a ledger to expose metadata
about the token to facilitate integration with wallets and user
interfaces: name, symbol, the number of decimal places for user display,
icon, official web page, etc.
The new API makes some of the previous methods (`symbol`, `name`,
`decimals`) excessive, but we still keep them because some ecosystem players
want to use explicitly named endpoints.
https://forum.dfinity.org/t/extensible-metadata-api-in-the-icrc-1-token-standard/13866/2
> Proposal: extensible metadata API

- README.md
I think `SubAccount` should be specified, and it would be nice to have an `Account` type instead of a separate principal and optional SubAccount everywhere.
> Account and SubAccount types

- ICRC-1.did
- README.md
The `Account` type is a combination of a principal and a subaccount. The subaccount was correctly called "subaccount" but the principal was called "of" for some reason. In the context of the `icrc1_balance_of` method, this makes sense. However, in the context of `icrc2_transfer` it does not.
In the future we may implement even more methods where "of" doesn't make sense as the name of the principal. By separating the usage from the definition, `Account` will remain flexible for all these use cases.
Additionally, when #26 was merged in we didn't update the did file. This takes care of that.
> Proposal: Rename principal in `Account` type

- ICRC-1.did
- README.md
This change
* Adds the missing TransferError definition to the standard.
* Describes the semantics of memo and created_at_time fields
and what error the client can expect.
* Updates the type of GenericError to be more useful.
> fix #31: add TransferError to the standard description

- ICRC-1.did
- README.md
- ref/ICRC1.mo
This change proposes to extend memos from 8 bytes to a blob of at least
32 bytes in length.
This change has been discussed in the Working Group and suggested again in #30.
> Proposal: larger memos

- ICRC-1.did
- README.md
For when a ledger wants to slow down the rate of the transfer calls. 
sample use case: to maintain a max-number of transactions in a single-canister's memory to check for a duplicate-transaction within a time-window.
> TransferError - TemporarilyUnavailable

- ICRC-1.did
- README.md
- ref/ICRC1.mo
The working group decided to rename `Account.principal` to `Account.owner`
because "principal" is a reserved symbol in Candid, which might create
unnecessary friction for people trying to call the ledger using dfx.
> Proposal: Account.principal → Account.owner

- README.md
In #43, we updated the definition of TransferError, but didn't update
the deduplication spec accordingly. This change fixes that omission.
Fixes #49.
> fix(#49): make dedup spec consistent with TransferError

- standards/ICRC-2/ICRC-2.did
ApproveArgs is missing this field in the did file
> fix: add missing `from_subaccount` in ICRC-2.did

- standards/ICRC-2/README.md
This change updates the ICRC-2 spec according to the WG decision to cap allowances instead of rejecting the `approve` calls on overflow.
This design is also more symmetric because we cap allowances to 0 when they go negative.
> fix(ICRC-2): cap max allowance

- standards/ICRC-1/README.md
Add a logo to the metadata using data urls.
Fixes #64.
> feat: specify the `icrc1:logo` metadata field

- ref/ICRC1.mo
- standards/ICRC-2/ICRC-2.did
- standards/ICRC-2/README.md
This change incorporates the feedback from the Working Group session on 2023-04-18:
1. We change the semantics of approvals to be closer to ERC-20. A call to icrc2_approve overwrites the previous allowance and the timestamp.
2. Allowances target accounts, not principals. This change will enable fine-grained control in DApps and significantly simplify implementation for ledgers that rely on AccountIdentifiers internally, such as the ICP ledger.
3. For applications that need concurrent approvals, we add optional "compare and swap" semantics of approvals. If the caller specifies the optional `expected_allowance` field, the ledger will return an error if the allowance changes before the ledger accepts the `approve` call.
TODO: update the reference implementation once we agree on the …
> feat: use ERC-20 semantics for approvals

- ref/Account.mo
- ref/AccountTest.mo
- ref/BUILD.bazel
- standards/ICRC-1/TextualEncoding.md
This change proposes a textual encoding for ICRC-1 accounts.
> feat: textual encoding for ICRC-1 account

- test/suite/lib.rs
This MR introduces the transfer error tests.
It tests whether the ledger recognized fees correctly, supports at least 32 bytes memos and whether transactions cannot be created in the future.
> feat(FI-860) transfer error tests

- test/ref/test.rs
- test/runner/main.rs
- test/suite/lib.rs
This MR suggests the following changes:
- Add a test suite for the ICRC-2 standard
- Add a test for the endpoint icrc1_supported_standard for the ICRC-2 standard
> feat(FI-866) add support for ICRC-2 standard

- Cargo.Bazel.lock
- Cargo.lock
- Cargo.toml
Commit 8af698 downgraded `serde` to version `1.0.171` due to an issue with precompiled macros. This issue was resolved in version `1.0.184`: https://github.com/serde-rs/serde/releases/tag/v1.0.184
> chore: update `serde` to version ^1.0.184.

- Charters.md
> dso-charters-20231114.md

- Cargo.Bazel.lock
- Cargo.lock
- Cargo.toml
- bazel/replica_tools.bzl
- test/ref/test.rs
- test/replica/lib.rs
- test/runner/main.rs
- test/suite/lib.rs
The IC repo has a dependency on this repo. In order to upgrade candid throughout the IC repo we need to bump it here first.
Due to a change in handling how absent paths in trees are certified (see [here](https://github.com/dfinity/agent-rs/pull/453)), an update of the referenced IC commit is necessary as well.
> chore: Upgrade candid and agent-rs

- .github/workflows/ci.yml
The CI workflow currently fails for most/all PRs since `v1` of `actions/cache` is no longer supported (see e.g., [this workflow run](https://github.com/dfinity/ICRC-1/actions/runs/17473950694/job/49629044996?pr=200)). This PR proposes to bump the version to `v3` as suggested in the error message in the failed workflow run.
> chore: FI-1858: Update actions/cache to v3

- Cargo.Bazel.lock
- Cargo.lock
- test/env/Cargo.toml
- test/env/Changelog.md
- test/env/replica/Cargo.toml
- test/env/replica/Changelog.md
- test/env/state-machine/Cargo.toml
- test/env/state-machine/Changelog.md
- test/replica/Cargo.toml
- test/replica/Changelog.md
- test/runner/Cargo.toml
- test/runner/Changelog.md
- test/suite/Cargo.toml
- test/suite/Changelog.md
Bump the crate versions to `0.1.12` and mark the `icrc1-test-env-state-machine` as deprecated, since it will be migrated to/replaced by the `icrc1-test-env-pocket-ic` crate.
> chore: FI-1858: Bump crate versions and deprecate icrc1-test-env-state-machine
